### ISSUE TITLE
Mouse shrink a lot on Pop!_OS in browsers

### ISSUE THREAD

**Issue by SilentGlasses** [alvatip/Nordzy-cursors#5] opened 2023-09-14 20:16 UTC
Having an interesting issue where when I apply your pointers, in Brave and Firefox (haven't tried other browsers) the cursors shrink by a large amount. It does not happen with the default Pop or Adwaita pointers however.

## Screenshots

![PXL_20230914_201351917](https://github.com/alvatip/Nordzy-cursors/assets/22822565/8c961869-2592-4bf9-8515-c201be1ab018)
![PXL_20230914_201341943](https://github.com/alvatip/Nordzy-cursors/assets/22822565/042623e2-a993-48e6-9d9b-4904c721d846)

**Comment by SilentGlasses** [comment] 2023-09-14 20:21
Found this...    If I run these commands it seems to work...

```
flatpak --user override --filesystem=/home/$USER/.icons/:ro
flatpak --user override --filesystem=/usr/share/icons/:ro
```

**Comment by alvatip** [comment] 2023-12-04 20:35
Hey @SilentGlasses ,
Sorry I wasn't notified when you opened the issue, I will have a look at this asap

**Comment by alvatip** [comment] 2023-12-05 21:39
I remember having issues with cursors and flatpak applications, I was not able to reproduce the issues on Fedora Linux 38 with either default or flatpak applications, in case flatpak applications still present an issue, below is an explanation + alternative solution from another site that might help:
"
Flatpak apps run sandboxed so they don't have access to your home folder where the themes are stored.

You can manually give access to it by installing Flatseal, an app to edit flatpaks permissions. Check the "All user files" button in the "Filesystem" section for Anki in Flatseal and the problem will be fixed.
"
Since issue is not reproducible on my system I couldn't try but installing the cursor system wide might fix the issue and explain why default cursors does not present the issue

**Closed by alvatip** 2023-12-05 21:39 UTC
